complete -c errno-grep --no-files -a "EPERM" -d "Operation not permitted"
complete -c errno-grep --no-files -a "ENOENT" -d "No such file or directory"
complete -c errno-grep --no-files -a "ESRCH" -d "No such process"
complete -c errno-grep --no-files -a "EINTR" -d "Interrupted system call"
complete -c errno-grep --no-files -a "EIO" -d "I/O error"
complete -c errno-grep --no-files -a "ENXIO" -d "No such device or address"
complete -c errno-grep --no-files -a "E2BIG" -d "Argument list too long"
complete -c errno-grep --no-files -a "ENOEXEC" -d "Exec format error"
complete -c errno-grep --no-files -a "EBADF" -d "Bad file number"
complete -c errno-grep --no-files -a "ECHILD" -d "No child processes"
complete -c errno-grep --no-files -a "EAGAIN" -d "Try again"
complete -c errno-grep --no-files -a "EWOULDBLOCK" -d "Operation would block"
complete -c errno-grep --no-files -a "ENOMEM" -d "Out of memory"
complete -c errno-grep --no-files -a "EACCES" -d "Permission denied"
complete -c errno-grep --no-files -a "EFAULT" -d "Bad address"
complete -c errno-grep --no-files -a "ENOTBLK" -d "Block device required"
complete -c errno-grep --no-files -a "EBUSY" -d "Device or resource busy"
complete -c errno-grep --no-files -a "EEXIST" -d "File exists"
complete -c errno-grep --no-files -a "EXDEV" -d "Cross-device link"
complete -c errno-grep --no-files -a "ENODEV" -d "No such device"
complete -c errno-grep --no-files -a "ENOTDIR" -d "Not a directory"
complete -c errno-grep --no-files -a "EISDIR" -d "Is a directory"
complete -c errno-grep --no-files -a "EINVAL" -d "Invalid argument"
complete -c errno-grep --no-files -a "ENFILE" -d "File table overflow"
complete -c errno-grep --no-files -a "EMFILE" -d "Too many open files"
complete -c errno-grep --no-files -a "ENOTTY" -d "Not a typewriter"
complete -c errno-grep --no-files -a "ETXTBSY" -d "Text file busy"
complete -c errno-grep --no-files -a "EFBIG" -d "File too large"
complete -c errno-grep --no-files -a "ENOSPC" -d "No space left on device"
complete -c errno-grep --no-files -a "ESPIPE" -d "Illegal seek"
complete -c errno-grep --no-files -a "EROFS" -d "Read-only file system"
complete -c errno-grep --no-files -a "EMLINK" -d "Too many links"
complete -c errno-grep --no-files -a "EPIPE" -d "Broken pipe"
complete -c errno-grep --no-files -a "EDOM" -d "Math argument out of domain of func"
complete -c errno-grep --no-files -a "ERANGE" -d "Math result not representable"
complete -c errno-grep --no-files -a "EDEADLK" -d "Resource deadlock would occur (EDEADLOCK)"
complete -c errno-grep --no-files -a "ENAMETOOLONG" -d "File name too long"
complete -c errno-grep --no-files -a "ENOLCK" -d "No record locks available"
complete -c errno-grep --no-files -a "ENOSYS" -d "Function not implemented"
complete -c errno-grep --no-files -a "ENOTEMPTY" -d "Directory not empty"
complete -c errno-grep --no-files -a "ELOOP" -d "Too many symbolic links encountered"
complete -c errno-grep --no-files -a "ENOMSG" -d "No message of desired type"
complete -c errno-grep --no-files -a "EIDRM" -d "Identifier removed"
complete -c errno-grep --no-files -a "ECHRNG" -d "Channel number out of range"
complete -c errno-grep --no-files -a "EL2NSYNC" -d "Level 2 not synchronized"
complete -c errno-grep --no-files -a "EL3HLT" -d "Level 3 halted"
complete -c errno-grep --no-files -a "EL3RST" -d "Level 3 reset"
complete -c errno-grep --no-files -a "ELNRNG" -d "Link number out of range"
complete -c errno-grep --no-files -a "EUNATCH" -d "Protocol driver not attached"
complete -c errno-grep --no-files -a "ENOCSI" -d "No CSI structure available"
complete -c errno-grep --no-files -a "EL2HLT" -d "Level 2 halted"
complete -c errno-grep --no-files -a "EBADE" -d "Invalid exchange"
complete -c errno-grep --no-files -a "EBADR" -d "Invalid request descriptor"
complete -c errno-grep --no-files -a "EXFULL" -d "Exchange full"
complete -c errno-grep --no-files -a "ENOANO" -d "No anode"
complete -c errno-grep --no-files -a "EBADRQC" -d "Invalid request code"
complete -c errno-grep --no-files -a "EBADSLT" -d "Invalid slot"
complete -c errno-grep --no-files -a "EBFONT" -d "Bad font file format"
complete -c errno-grep --no-files -a "ENOSTR" -d "Device not a stream"
complete -c errno-grep --no-files -a "ENODATA" -d "No data available"
complete -c errno-grep --no-files -a "ETIME" -d "Timer expired"
complete -c errno-grep --no-files -a "ENOSR" -d "Out of streams resources"
complete -c errno-grep --no-files -a "ENONET" -d "Machine is not on the network"
complete -c errno-grep --no-files -a "ENOPKG" -d "Package not installed"
complete -c errno-grep --no-files -a "EREMOTE" -d "Object is remote"
complete -c errno-grep --no-files -a "ENOLINK" -d "Link has been severed"
complete -c errno-grep --no-files -a "EADV" -d "Advertise error"
complete -c errno-grep --no-files -a "ESRMNT" -d "Srmount error"
complete -c errno-grep --no-files -a "ECOMM" -d "Communication error on send"
complete -c errno-grep --no-files -a "EPROTO" -d "Protocol error"
complete -c errno-grep --no-files -a "EMULTIHOP" -d "Multihop attempted"
complete -c errno-grep --no-files -a "EDOTDOT" -d "RFS specific error"
complete -c errno-grep --no-files -a "EBADMSG" -d "Not a data message"
complete -c errno-grep --no-files -a "EOVERFLOW" -d "Value too large for defined data type"
complete -c errno-grep --no-files -a "ENOTUNIQ" -d "Name not unique on network"
complete -c errno-grep --no-files -a "EBADFD" -d "File descriptor in bad state"
complete -c errno-grep --no-files -a "EREMCHG" -d "Remote address changed"
complete -c errno-grep --no-files -a "ELIBACC" -d "Can not access a needed shared library"
complete -c errno-grep --no-files -a "ELIBBAD" -d "Accessing a corrupted shared library"
complete -c errno-grep --no-files -a "ELIBSCN" -d ".lib section in a.out corrupted"
complete -c errno-grep --no-files -a "ELIBMAX" -d "Attempting to link in too many shared libraries"
complete -c errno-grep --no-files -a "ELIBEXEC" -d "Cannot exec a shared library directly"
complete -c errno-grep --no-files -a "EILSEQ" -d "Illegal byte sequence"
complete -c errno-grep --no-files -a "ERESTART" -d "Interrupted system call should be restarted"
complete -c errno-grep --no-files -a "ESTRPIPE" -d "Streams pipe error"
complete -c errno-grep --no-files -a "EUSERS" -d "Too many users"
complete -c errno-grep --no-files -a "ENOTSOCK" -d "Socket operation on non-socket"
complete -c errno-grep --no-files -a "EDESTADDRREQ" -d "Destination address required"
complete -c errno-grep --no-files -a "EMSGSIZE" -d "Message too long"
complete -c errno-grep --no-files -a "EPROTOTYPE" -d "Protocol wrong type for socket"
complete -c errno-grep --no-files -a "ENOPROTOOPT" -d "Protocol not available"
complete -c errno-grep --no-files -a "EPROTONOSUPPORT" -d "Protocol not supported"
complete -c errno-grep --no-files -a "ESOCKTNOSUPPORT" -d "Socket type not supported"
complete -c errno-grep --no-files -a "EOPNOTSUPP" -d "Operation not supported on transport endpoint"
complete -c errno-grep --no-files -a "EPFNOSUPPORT" -d "Protocol family not supported"
complete -c errno-grep --no-files -a "EAFNOSUPPORT" -d "Address family not supported by protocol"
complete -c errno-grep --no-files -a "EADDRINUSE" -d "Address already in use"
complete -c errno-grep --no-files -a "EADDRNOTAVAIL" -d "Cannot assign requested address"
complete -c errno-grep --no-files -a "ENETDOWN" -d "Network is down"
complete -c errno-grep --no-files -a "ENETUNREACH" -d "Network is unreachable"
complete -c errno-grep --no-files -a "ENETRESET" -d "Network dropped connection because of reset"
complete -c errno-grep --no-files -a "ECONNABORTED" -d "Software caused connection abort"
complete -c errno-grep --no-files -a "ECONNRESET" -d "Connection reset by peer"
complete -c errno-grep --no-files -a "ENOBUFS" -d "No buffer space available"
complete -c errno-grep --no-files -a "EISCONN" -d "Transport endpoint is already connected"
complete -c errno-grep --no-files -a "ENOTCONN" -d "Transport endpoint is not connected"
complete -c errno-grep --no-files -a "ESHUTDOWN" -d "Cannot send after transport endpoint shutdown"
complete -c errno-grep --no-files -a "ETOOMANYREFS" -d "Too many references: cannot splice"
complete -c errno-grep --no-files -a "ETIMEDOUT" -d "Connection timed out"
complete -c errno-grep --no-files -a "ECONNREFUSED" -d "Connection refused"
complete -c errno-grep --no-files -a "EHOSTDOWN" -d "Host is down"
complete -c errno-grep --no-files -a "EHOSTUNREACH" -d "No route to host"
complete -c errno-grep --no-files -a "EALREADY" -d "Operation already in progress"
complete -c errno-grep --no-files -a "EINPROGRESS" -d "Operation now in progress"
complete -c errno-grep --no-files -a "ESTALE" -d "Stale NFS file handle"
complete -c errno-grep --no-files -a "EUCLEAN" -d "Structure needs cleaning"
complete -c errno-grep --no-files -a "ENOTNAM" -d "Not a XENIX named type file"
complete -c errno-grep --no-files -a "ENAVAIL" -d "No XENIX semaphores available"
complete -c errno-grep --no-files -a "EISNAM" -d "Is a named type file"
complete -c errno-grep --no-files -a "EREMOTEIO" -d "Remote I/O error"
complete -c errno-grep --no-files -a "EDQUOT" -d "Quota exceeded"
complete -c errno-grep --no-files -a "ENOMEDIUM" -d "No medium found"
complete -c errno-grep --no-files -a "EMEDIUMTYPE" -d "Wrong medium type"
complete -c errno-grep --no-files -a "ECANCELED" -d "Operation Canceled"
complete -c errno-grep --no-files -a "ENOKEY" -d "Required key not available"
complete -c errno-grep --no-files -a "EKEYEXPIRED" -d "Key has expired"
complete -c errno-grep --no-files -a "EKEYREVOKED" -d "Key has been revoked"
complete -c errno-grep --no-files -a "EKEYREJECTED" -d "Key was rejected by service"
complete -c errno-grep --no-files -a "EOWNERDEAD" -d "Owner died"
complete -c errno-grep --no-files -a "ENOTRECOVERABLE" -d "State not recoverable"
